repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.3.0"
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-merge-conflict
-   repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
    -   id: flake8
        name: "Flake8: critical"
        args: ['--count', '--select=E9,F63,F7,F82', '--show-source', '--statistics']
